<a href="https://colab.research.google.com/github/ritzx/dictionarymappings/blob/master/ml2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import sklearn
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn import tree

import numpy as np
iris = load_iris()
print (iris.feature_names)
print (iris.target_names)
digits = datasets.load_digits()
print(digits.data) 
  
print (iris.data[0])
print (iris.target[0])
test_idx = [0,50,100]

#training data
train_target = np.delete(iris.target,test_idx)
train_data=np.delete(iris.data,test_idx,axis=0)

#testing data
test_target=iris.target[test_idx]
test_data=iris.data[test_idx]

clf=tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print (test_target)
print (clf.predict(test_data))

#vizcode



                   










['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[5.1 3.5 1.4 0.2]
0
[0 1 2]
[0 1 2]
